# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  #i386: "ghcr.io/home-assistant/i386-base:3.15"
  #aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  #armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  #armv7: "ghcr.io/home-assistant/armv7-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/thimslugga/haos-addons-thimslugga"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.08.30"
